refactor(git-bb): fix for 'fatal: ambiguous argument 'xxx': both revision and filename' issue
Signed-off-by: marslo <marslo.jiao@gmail.com>

diff --git a/.marslo/bin/git-bb b/.marslo/bin/git-bb
--- a/.marslo/bin/git-bb
+++ b/.marslo/bin/git-bb
@@ -17,10 +17,24 @@ function isGHE() {
   git remote get-url origin | grep -qE '(git@|https://).+[:/]Marvell-[^/]+/'
 }
 
+# shellcheck disable=SC2155,SC2016
 function getBranch() {
-  # shellcheck disable=SC2155
-  local current="$(git branch --show-current)"
-  local gpreview="git show --color=always {-1}"
+  local current="$(git symbolic-ref -q HEAD)"
+  local showPager=$(git config pager.show)
+  export _pager="${showPager:+| ${showPager} --color=always}"
+
+  local gpreview='bash -c '"'"'
+    ref="{-1}"
+    [[ $ref == origin/* ]] && ref="refs/remotes/${ref}" || ref="refs/heads/${ref}"
+    eval "git show --color=always ${ref} ${_pager}"
+  '"'"
+
+  local gpreviewS='bash -c '"'"'
+    ref="{-1}"
+    [[ $ref == origin/* ]] && ref="refs/remotes/${ref}" || ref="refs/heads/${ref}"
+    eval "git show --color=always -s ${ref} ${_pager}"
+  '"'"
+
   # git remote set-head origin --auto
   test -f "$(git rev-parse --absolute-git-dir)"/refs/remotes/origin/HEAD &&
     main="$(git symbolic-ref --short refs/remotes/origin/HEAD | sed 's|^origin/||')" ||
@@ -33,23 +47,32 @@ function getBranch() {
                  } |
                  grep -v --color=never -E "^(${current}|origin/${current})$" |
                  # awk 'NF && !seen[$0]++'
-                 awk -v cur="${current}" -v remote=$'\033[0;3m' -v local=$'\033[0;32m' -v reset=$'\033[0m' '
-                   NF  { a[++n] = $0; if ( $0 !~ /^origin\// ) L[$0] = 1; }
-                   END {
-                         for (i = 1; i <= n; i++) {
-                           x = a[i]
-                           if ( S[x]++ || x == "origin" || x == cur ) continue
-                           if ( x ~ /^origin\// ) { if ( L[substr(x, 8)] ) continue; print remote x reset }
-                           else { print local x reset }
-                         }
-                   }' |
+                 awk -v cur="${current}" \
+                     -v remote=$'\033[0;3m' \
+                     -v local=$'\033[0;32m' \
+                     -v reset=$'\033[0m' \
+                     -v ALL="${SHOW_ALL}" '
+                      NF  { a[++n] = $0; if ( $0 !~ /^origin\// ) L[$0] = 1; }
+                      END {
+                            for (i = 1; i <= n; i++) {
+                              x = a[i]
+                              if ( S[x]++ || x == "origin" || x == cur ) continue
+                              if ( x ~ /^origin\// ) {
+                                if ( !ALL && L[substr(x, 8)] ) continue
+                                print remote x reset
+                              } else {
+                                print local x reset
+                              }
+                            }
+                      }' |
                 fzf +m --ansi --prompt=' ' -0 \
                      --height 50% --min-height 10+ \
                      --style full --no-input-border \
-                     --preview "${gpreview} -s" \
+                     --preview "${gpreviewS}" \
+                     --info='inline-right' \
                      --preview-window=right,55%,nofollow --preview-label-pos='bottom' \
-                     --bind "ctrl-o:execute(${gpreview})+change-preview(${gpreview} -s)+change-prompt( )" \
-                     --bind 'ctrl-/:change-preview-window:up,60%|hidden|right,55%' \
+                     --bind "ctrl-o:execute(${gpreview})+change-preview(${gpreviewS})+change-prompt( )" \
+                     --bind 'ctrl-\:change-preview-window:up,60%|hidden|right,55%' \
                      --bind 'ctrl-y:execute-silent(git log {-1} -1 --pretty=format:"%H" | pbcopy)' |
                  sed -rn "s:\s*(origin/)?(.*)$:\2:p"
                 )
@@ -61,14 +84,29 @@ git rev-parse --is-inside-work-tree >/dev/null 2>&1 || {
   exit 128
 }
 
+declare FORCE
+declare SHOW_ALL=false
+
+while [[ $# -gt 0 ]]; do
+  case "$1" in
+    -f | --force ) FORCE=true ; shift ;;
+    -a | --all   ) SHOW_ALL=true; shift ;;
+    *            ) echo "ERROR: unknown option '$1'"; exit 1;;
+  esac
+done
+
 if [[ $# -eq 1 ]]; then
   branch="$1"
 else
   branch="$(getBranch)"
 fi
 
-[[ -n "${branch:-}" ]] &&
-printf "\033[1;33m~~> %s\033[0m\n" "${branch}" &&
-git checkout --force "${branch}"
+if [[ -n "${branch:-}" ]]; then
+  printf "\033[0;37;2;3m~~> %b\033[0;33;1m%s\033[0m\n" "${FORCE:+\033[0;35;3;1mforce \033[0;37;2;3mcheckout\033[0m }" "${branch}"
+
+  declare -a cmd=( git checkout "${branch}" )
+  ${FORCE:-false} && cmd+=( --force ) || :
+  "${cmd[@]}"
+fi
 
 # vim:tabstop=2:softtabstop=2:shiftwidth=2:expandtab:filetype=sh:
