feat(fzfInPath,git-mi,glogsmart): enable fzfInPath to use `--strip-cwd-prefix` automatically; enable `-r/--revision` in git-mi; introduce glogsmart language for bat
- make fzfInPath automatically enable/disable `--strip-cwd-prefix`
- enable revision feature in git-mi, to rebase automatically with the revision number
- introduce `GitLogSmart.sublime-syntax` in bat; and use bat for git show pager (theme - OneHalfDark)

Signed-off-by: marslo <marslo.jiao@gmail.com>

diff --git a/.marslo/bin/git-rr b/.marslo/bin/git-rr
--- a/.marslo/bin/git-rr
+++ b/.marslo/bin/git-rr
@@ -1,9 +1,15 @@
 #!/usr/bin/env bash
-# shellcheck source=/dev/null
+# shellcheck source=/dev/null disable=SC2155
+#=============================================================================
+#     FileName : git-rr
+#       Author : marslo
+#      Created : 2023-01-12 20:36:04
+#   LastChange : 2026-03-07 02:31:41
+#=============================================================================
 
 shopt -s extglob
 
-# shellcheck disable=SC2155
+declare -r ME="$(basename "${BASH_SOURCE[0]:-$0}" | sed 's/-/ /g')"
 declare -r HERE="$( dirname "${BASH_SOURCE[0]:-$0}" )"
 # @credit: https://github.com/ppo/bash-colors
 # @usage:  or copy & paste the `c()` function from:
@@ -11,12 +17,12 @@ declare -r HERE="$( dirname "${BASH_SOURCE[0]:-$0}" )"
 # shellcheck disable=SC2015
 test -f "${HERE}/bash-colors.sh" && source "${HERE}/bash-colors.sh" || { c() { :; }; }
 
-function die() { echo -e "$(c R)ERROR$(c) : $*" >&2; exit 2; }
-function exitOnError() { if [ $? -ne 0 ]; then echo -e "$(c R)ERROR$(c) : $*" >&2; exit 1; fi; }
-function showHelp() { echo -e "${usage}"; exit 0; }
+function die() { echo -e "$(c Rs)ERROR$(c) : $*" >&2; exit 2; }
+function exitOnError() { if [ $? -ne 0 ]; then echo -e "$(c Rs)ERROR$(c) : $*" >&2; exit 1; fi; }
+function showHelp() { echo -e "${USAGE}"; exit 0; }
 function needsArg() { [[ -z "$OPTARG" ]] && die "no arg for --$OPT option"; }
 function isRepo() { git rev-parse --git-dir >/dev/null 2>&1 || exitOnError 'not a git repo !'; }
-function getRevision() { sha=$(git rev-parse -q --verify "$1^{commit}"); echo "${sha}"; }
+function getRevision() { git rev-parse -q --verify "$1^{commit}"; }
 function trim() { IFS='' read -r str; echo "${str}" | sed -e 's/^[[:blank:]]*//;s/[[:blank:]]*$//'; }
 
 function showParams() {
@@ -36,8 +42,8 @@ function showParams() {
   $(c M)commitEmail$(c) : '${commitEmail}'
    $(c M)commitDate$(c) : '${commitDate}'
        $(c M)params$(c) : $(c G)
-                 git rr -a '${author}' -e '${authorEmail}' -d '${authorDate}' -c '${committer}' -E '${commitEmail}' -D '${commitDate}'
-                 git rr --author=\"${author}\" --authorEmail=\"${authorEmail}\" --authorDate=\"${authorDate}\" --committer=\"${committer}\" --commitEmail=\"${commitEmail}\" --commitDate=\"${commitDate}\"$(c)
+                 ${ME} -a '${author}' -e '${authorEmail}' -d '${authorDate}' -c '${committer}' -E '${commitEmail}' -D '${commitDate}'
+                 ${ME} --author=\"${author}\" --authorEmail=\"${authorEmail}\" --authorDate=\"${authorDate}\" --committer=\"${committer}\" --commitEmail=\"${commitEmail}\" --commitDate=\"${commitDate}\"$(c)
   $(c M)environment$(c) : $(c C)
                  export GIT_AUTHOR_NAME='${author}'
                  export GIT_AUTHOR_EMAIL='${authorEmail}'
@@ -55,7 +61,7 @@ function getInfo() {
   echo -n "$(eval "${command}" || exitOnError 'failed to get revision information')"
 }
 
-function doSetEnv() {
+function setEnv() {
   [[ 6 -ne $# ]] && die "wrong parameters in showParams function"
   local author=$1
   local authorEmail=$2
@@ -87,7 +93,7 @@ function doSetEnv() {
   """
 }
 
-function doUnSetEnv() {
+function unsetEnv() {
   GIT_COMMIT_ENV="GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL GIT_AUTHOR_DATE GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL GIT_COMMITTER_DATE";
   for envvar in ${GIT_COMMIT_ENV}; do unset "${envvar}"; done;
   echo -e """
@@ -100,6 +106,7 @@ function doUnSetEnv() {
   exit 0
 }
 
+# call git-mi
 function doModify() {
   [[ 6 -ne $# ]] && die "wrong parameters in doModify function"
   local author=$1
@@ -108,46 +115,47 @@ function doModify() {
   local committer=$4
   local commitEmail=$5
   local commitDate=$6
-  local cmd="""bash "${dir}/git-mi" --author=\"${author}\" --authorEmail=\"${authorEmail}\" --authorDate=\"${authorDate}\" --committer=\"${committer}\" --commitEmail=\"${commitEmail}\" --commitDate=\"${commitDate}\" """
-  eval "${cmd}" || exitOnError 'failed to modify revision information'
+  local -a cmd=( bash "${HERE}/git-mi" --author="${author}" --authorEmail="${authorEmail}" --authorDate="${authorDate}" --committer="${committer}" --commitEmail="${commitEmail}" --commitDate="${commitDate}" )
+  "${cmd[@]}" || exitOnError 'failed to modify revision information (via git-mi)'
 }
 
+declare SHOW_DEFAULT=false
+declare VERBOSE=false
+declare CHERRY_PICK=false
+declare SETENV=false
+declare sha=''
+# shellcheck disable=SC2155
+declare -r USAGE="NAME
+  $(c Ys)${ME}$(c) - $(c Ys)r$(c)evision $(c Ys)r$(c)eset - to reset the git revision author/authorEmail/authorDates/committer/commitEmail/commitDate
 
-help='false'
-default='false'
-verbose='false'
-cherryPick='false'
-setEnv='false'
-unSetEnv='false'
-sha=''
-usage="""
-\t $(c R)git-rr$(c) - $(c iR)r$(c)evision $(c iR)r$(c)eset: to reset the git revision author/authorEmail/authorDates/committer/commitEmail/commitDate
-\nSYNOPSIS:
-\n\t$(c sY)\$ git rr [ -v | --verbose | --debug ]
-\t\t [ -h | --help ]
-\t\t [ -d | --default ]
-\t\t [ -s | --set ]
-\t\t [ -u | --unSet ]
-\t\t [ -c | --cp | --cherry-pick ]
-\t\t [ -r | --revision <sha1> ]$(c)
-\nEXAMPLE:
-\n\tshow help
-\t\t$(c G)\$ git rr $(c)| $(c G)\$ git rr -h$(c) | $(c G)\$ git rr --help$(c)
-\n\tget verbose
-\t\t$(c G)\$ git rr -v$(c) | $(c G)\$ git rr --verbose$(c) | $(c G)\$ git rr --debug$(c)
-\n\tto set the author/committer to default ( from git config )
-\t\t$(c G)\$ git rr -d --revision=<revision>$(c) | $(c G)\$ git rr -d -r <revision>$(c)
-\n\tto cherry-pick and reset revision information
-\t\t$(c G)\$ git rr -c --revision=<revision>$(c) | $(c G)\$ git rr -c -r <revision>$(c)
-\t\t\t\t      + the long parameters MUST use '$(c R)=$(c)' to identify opt and args
-\n\tto reset revision information only
-\t\t$(c G)\$ git rr --revision=<revision>$(c) | $(c G)\$ git rr -r <revision>$(c)
-\t\t\t\t   + the long parameters MUST use '$(c R)=$(c)' to identify opt and args
-\n\tto reset revision information and setup the commit/push environment
-\t\t$(c G)\$ git rr --set --revision=<revision>$(c) | $(c G)\$ git rr -s -r <revision>$(c)
-\n\tto remove all git commit environment variables
-\t\t$(c G)\$ git rr -u$(c) | $(c G)git rr --unset$(c)
-"""
+SYNOPSIS
+  $(c Ys)\$ ${ME} $(c 0G)[options] $(c 0Mi)<sha1|refspec>$(c)
+
+OPTIONS
+  $(c G)-s$(c), $(c G)--set$(c)                reset revision information and setup the commit/push environment
+  $(c G)-u$(c), $(c G)--unset$(c)              remove all git commit environment variables
+  $(c G)-c$(c), $(c G)--cp$(c), $(c G)--cherry-pick$(c)  cherry-pick the revision to current branch
+  $(c G)-r$(c), $(c G)--revision$(c 0Cs)=$(c 0Mi)<sha1>$(c)    reset revision information to the specified revision
+  $(c G)-d$(c), $(c G)--default$(c)            set the author/committer to default ( from git config )
+  $(c G)-v$(c), $(c G)--verbose$(c), $(c G)--debug$(c)   get verbose revision information
+  $(c G)-h$(c)                       show this help message and exit
+
+EXAMPLE
+  $(c Wdi)# show verbose$(c)
+  $(c Y)\$ ${ME} $(c 0Gi)-v$(c 0Wd) | $(c 0Y)\$ ${ME} $(c 0Gi)--verbose$(c 0Wd) | $(c 0Y)\$ ${ME} $(c 0Gi)--debug$(c)
+  $(c Wdi)# to set the author/committer to default ( from git config )$(c)
+  $(c Y)\$ ${ME} $(c 0Gi)-d --revision$(c 0Cs)=$(c 0Mi)<revision>$(c 0Wd) | $(c 0Y)\$ ${ME} $(c 0Gi)-d -r $(c 0Mi)<revision>$(c)
+  $(c Wdi)# to cherry-pick and reset revision information$(c)
+  $(c Y)\$ ${ME} $(c 0Gi)-c --revision$(c 0Cs)=$(c 0Mi)<revision>$(c 0Wd) | $(c 0Y)\$ ${ME} $(c 0Gi)-c -r $(c 0Mi)<revision>$(c)
+                        $(c Wi)+ the long parameters MUST use $(c 0Cs)'='$(c 0Wi) to identify opt and args$(c)
+  $(c Wdi)# to reset revision information only$(c)
+  $(c Y)\$ ${ME} $(c 0Gi)--revision$(c 0Cs)=$(c 0Mi)<revision>$(c 0Wd) | $(c 0Y)\$ ${ME} $(c 0Gi)-r $(c 0Mi)<revision>$(c)
+                     $(c Wi)+ the long parameters MUST use $(c 0Cs)'='$(c 0Wi) to identify opt and args$(c)
+  $(c Wdi)# to reset revision information and setup the commit/push environment$(c)
+  $(c Y)\$ ${ME} $(c 0Gi)--set --revision$(c 0Cs)=$(c 0Mi)<revision>$(c 0Wd) | $(c 0Y)\$ ${ME} $(c 0Gi)-s -r $(c 0Mi)<revision>$(c)
+  $(c Wdi)# to remove all git commit environment variables$(c)
+  $(c Y)\$ ${ME} $(c 0Gi)-u$(c 0Wd) | $(c 0Y)${ME} $(c 0Gi)--unset$(c)
+"
 
 # for non '-' params
 if [[ 0 -eq $# ]]; then
@@ -157,7 +165,7 @@ elif [[ 1 -eq $# ]] && [[ '-' != "${1::1}" ]] && [[ "$1" =~ '=' ]]; then
   sha="$1"
 # for '-'/'--' params
 else
-  # credit belongs to https://stackoverflow.com/a/28466267/519360
+  # @credit: https://stackoverflow.com/a/28466267/519360
   # shellcheck disable=SC2295
   while getopts :hdsvcr:-: OPT; do
     if [ "$OPT" = "-" ]; then
@@ -166,12 +174,12 @@ else
       OPTARG="${OPTARG#=}"
     fi
     case "$OPT" in
-      h | help             ) help='true'                 ;;
-      d | default          ) default='true'              ;;
-      v | verbose | debug  ) verbose='true'              ;;
-      c | cp | cherry-pick ) cherryPick='true'           ;;
-      s | set              ) setEnv='true'               ;;
-      u | unSet            ) unSetEnv='true'             ;;
+      h                    ) showHelp                    ;;
+      d | default          ) SHOW_DEFAULT=true           ;;
+      v | verbose | debug  ) VERBOSE=true                ;;
+      c | cp | cherry-pick ) CHERRY_PICK=true            ;;
+      s | set              ) SETENV=true                 ;;
+      u | unset            ) unsetEnv                    ;;
       r | revision         ) needsArg; sha="$OPTARG"     ;;
       ??*                  ) die "Illegal option --$OPT" ;;
       ?                    ) die "Illegal option --$OPT" ;;
@@ -181,36 +189,34 @@ else
   shift $((OPTIND-1))
 fi
 
-[[ 'true' = "${help}"     ]] && showHelp
-[[ 'true' = "${unSetEnv}" ]] && doUnSetEnv
-
 isRepo
-dir=$(dirname "$0")
-revision=$(getRevision "${sha}")
+declare revision=$( getRevision "${sha}" )
 [[ -z "${revision}" ]] && die "ref '${sha}' cannot be found in current repo."
-shortRevision="${revision:0:10}"
+declare shortRevision="${revision:0:10}"
 
-values=$(getInfo "${revision}")
-authorDate=$(echo "${values}"   |  awk -F'|' '{print $3}' | trim)
-commitDate=$(echo "${values}"   |  awk -F'|' '{print $6}' | trim)
+declare values=$( getInfo "${revision}" )
+declare authorDate=$( echo "${values}"  | awk -F'|' '{print $3}' | trim )
+declare commitDate=$( echo "${values}"  | awk -F'|' '{print $6}' | trim )
 
-if [[ 'true' = "${default}" ]]; then
-  _name=$(git config user.name)
-  _email=$(git config user.email)
+declare author='' authorEmail='' committer='' commitEmail=''
+if "${SHOW_DEFAULT}"; then
+  declare _name='' _email=''
+  _name=$( git config user.name )
+  _email=$( git config user.email )
   author="${_name}"
   authorEmail="${_email}"
   committer="${_name}"
   commitEmail="${_email}"
 else
-  author=$(echo "${values}"       |  awk -F'|' '{print $1}' | trim)
-  authorEmail=$(echo "${values}"  |  awk -F'|' '{print $2}' | trim)
-  committer=$(echo "${values}"    |  awk -F'|' '{print $4}' | trim)
-  commitEmail=$(echo "${values}"  |  awk -F'|' '{print $5}' | trim)
+  author=$( echo "${values}"      | awk -F'|' '{print $1}' | trim )
+  authorEmail=$( echo "${values}" | awk -F'|' '{print $2}' | trim )
+  committer=$( echo "${values}"   | awk -F'|' '{print $4}' | trim )
+  commitEmail=$( echo "${values}" | awk -F'|' '{print $5}' | trim )
 fi
 
-[[ 'true' = "${verbose}"    ]] && showParams "${author}" "${authorEmail}" "${authorDate}" "${committer}" "${commitEmail}" "${commitDate}"
-[[ 'true' = "${cherryPick}" ]] && git cherry-pick "${revision}"
-[[ 'true' = "${setEnv}"     ]] && doSetEnv "${author}" "${authorEmail}" "${authorDate}" "${committer}" "${commitEmail}" "${commitDate}"
+"${VERBOSE}"     && showParams "${author}" "${authorEmail}" "${authorDate}" "${committer}" "${commitEmail}" "${commitDate}"
+"${CHERRY_PICK}" && git cherry-pick "${revision}"
+"${SETENV}"      && setEnv "${author}" "${authorEmail}" "${authorDate}" "${committer}" "${commitEmail}" "${commitDate}"
 doModify "${author}" "${authorEmail}" "${authorDate}" "${committer}" "${commitEmail}" "${commitDate}"
 
 if [[ -n "${revision}" ]]; then
