refactor(die): strengthen die() function; fix the next-url in ghperm; add verbose/vverbose mode in ghperm
Signed-off-by: marslo <marslo.jiao@gmail.com>

diff --git a/.marslo/bin/git-changed b/.marslo/bin/git-changed
--- a/.marslo/bin/git-changed
+++ b/.marslo/bin/git-changed
@@ -4,7 +4,7 @@
 #     FileName : git-changed
 #       Author : marslo
 #      Created : 2025-08-22 15:24:56
-#   LastChange : 2025-12-03 02:44:07
+#   LastChange : 2025-12-04 02:29:14
 #=============================================================================
 
 set -euo pipefail
@@ -57,11 +57,15 @@ EXAMPLES
 """
 
 function usage() { echo -e "${USAGE}"; exit 0; }
-function die()   { echo -e "$(c Ri)ERROR$(c)$(c i): $*.$(c) $(c 0Wdi)exit ...$(c)" >&2; }
+function die() {
+  local exitcode=1 msg; local -a args=( "$@" ); local last="${!#}";
+  [[ "${last}" =~ ^[0-9]+$ ]] && { exitcode="${last}"; unset "args[$(( ${#args[@]} - 1 ))]"; }
+  msg="${args[*]}"
+  echo -e "$(c Ri)ERROR$(c)$(c i): ${msg}.$(c) $(c 0Wdi)exit ...$(c)" >&2; exit "${exitcode}";
+}
 function main()  {
   if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
-    die "fatal: not a git repository (or any of the parent directories): .git"
-    return 128
+    die "fatal: not a git repository (or any of the parent directories): .git" '128'
   fi
 
   while [[ "$#" -gt 0 ]]; do
@@ -77,7 +81,7 @@ function main()  {
                             -h | --help ) usage                          ;;
                             *           ) shift; pathspec+=("$@"); set --; break ;;
                           esac                                           ;;
-      -*                ) die "error: unknown option: $1"; return 2      ;;
+      -*                ) die "error: unknown option: $1" "2"            ;;
       *                 ) pathspec+=("$1")                               ;;
     esac
     shift
